# Change these first
owner: MDJ # Your GitHub organization or username, where this repository lives
repo: karma-site-monitoring # The name of this repository

sites:
  - name: QA-portal-Karma
    url: https://staging.karmahealthcare.in/karma-app/staging/Login.html
  - name: Dev-portal-Karma
    url: https://staging.karmahealthcare.in/karma-app/testing/Login.html
  - name: Prod-portal-Karma
    url: https://karmahealthcare.in/karma-app/Management/Login.html
  - name: Staging-API-Karma
    url: https://staging.api.karmaprimaryhealthcare.in
  - name: Prod-API-Karma
    url: https://api.karmaprimaryhealthcare.in/api/auth/password_login
  - name: Prod-texttovid
    url: https://texttovid.devkraft.in/api/health
  - name: Prod-semantic
    url: https://semantic.devkraft.in/api/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /karma-site-monitoring
  logoUrl: https://karmahealthcare.in/assets/img/logo_new.png
  name: Status
  introTitle: "**Karma Healthcare** uptime monitor and status page"
  introMessage: This is a status page which give status of public urls
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
